#!/usr/bin/env sh

xcodebuild test \
    -workspace Patchwork.xcworkspace \
    -scheme LayoutTest \
    -sdk iphoneos \
    -destination 'name=iPhone 13 Pro Max'

xcodebuild test \
    -workspace Patchwork.xcworkspace \
    -scheme PerfTest \
    -sdk iphoneos \
    -destination 'name=iPhone 13 Pro Max'
