name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare Xcode Project for iOS Execution
        run: |
          swift package generate-xcodeproj

      - name: Build Test
        run: |
          xcodebuild build -sdk iphoneos -scheme 'Patchwork-Package'

      - name: Unit Test
        run: |
          xcodebuild test -destination 'name=iPhone 11' -scheme 'Patchwork-Package'
