name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prep
        run: |
          sw_vers
          xcodebuild -version

      - name: Build Test
        run: ./build

      - name: Unit Test
        run: ./test
